Get-ChildItem  
[[-Path] <string[]>]   
[[-Filter] <string>]  
[-Recurse]   
[-Depth <uint32>]   
[-Include <string[]>]   
[-Exclude <string[]>]  
[-Name]   
[-Force] [-Directory]   
[-Attributes <FlagsExpression[FileAttributes]>][-FollowSymlink]   
[-File]  
[-Hidden]  
[-System]  
[-ReadOnly]  
[<CommonParameters>]  